default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budget_development
  username: postgres
  password: Duque

test:
  <<: *default
  database: Budget_test
  username: postgres
  password: Duque

production:
  <<: *default
  database: Budget_production
  username: Budget
  password: <%= ENV["Budget_DATABASE_PASSWORD"] %>